/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Return the projected (tenor × delta-band) analytics grid for one ticker/day.
         *
         *     ``underlying`` defaults to the context default; ``trade_date`` left ``None`` reads across
         *     every persisted day for the underlying. A malformed ``trade_date`` yields a labeled 400; an
         *     unknown ticker or empty grid yields an empty ``maturities`` list with HTTP 200.
         */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attribution
         * @description Return one by-Greek attribution record's waterfall payload.
         *
         *     ``level`` selects the book aggregate (default) or one position (``position`` + ``contract_key``,
         *     the §5.8 drill target). With ``trade_date=None`` the store returns every partition and the
         *     record is selected in Python, so an unknown ``(portfolio, date)`` resolves to a labelled-empty
         *     body, not a 500. A malformed ``trade_date`` is a labelled 400.
         */
        get: operations["get_attribution_api_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/basket/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price Basket
         * @description Price and risk a composed basket off the stored Tab-1 analytics (read-only).
         *
         *     Reads the WS-1F analytics grid for the basket's ``(trade_date, underlying[, provider])`` and
         *     the stock-leg spots from ``daily_bar`` on the same date, then sums the per-leg dollar Greeks.
         *     Returns the priced/risked basket with each dollar number carrying its unit string and the
         *     per-leg breakdown + labelled gaps (HTTP 200). A malformed basket is a labelled 400.
         */
        post: operations["price_basket_api_basket_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/basket/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stress Basket
         * @description Full-reprice a composed basket over the cartesian (spot x vol) stress grid (WS 2B).
         *
         *     The interactive, no-cron counterpart to ``GET /api/risk/scenarios`` (which reads the cron's
         *     persisted surface): reconstructs a valuation per option leg from the stored WS-1F analytics
         *     grid (:mod:`..basket_scenarios`), reprices the basket over the config-driven surface, and
         *     returns the same surface payload shape the ``StressSurface`` web component renders plus the
         *     worst-case cell and labelled per-leg gaps. A malformed basket is a labelled 400; an
         *     unresolved leg is a labelled gap inside a 200, never a 500.
         */
        post: operations["stress_basket_api_basket_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Booking
         * @description Commit a previewed ticket into paper fill(s) behind the password gate (read-only, paper).
         *
         *     Builds the previewed ticket from the body, then runs the write barrier. A malformed request
         *     is a labelled 400; a gate refusal or an unresolvable leg is a labelled ``block`` (HTTP 200,
         *     no fill written); a verified, resolvable booking writes the fills + audit record and returns
         *     ``decision: "commit"``. **Nothing is transmitted to a broker.**
         */
        post: operations["commit_booking_api_booking_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Config Files
         * @description List the available config files (names only).
         */
        get: operations["list_config_files_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/delta-bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Delta Bands
         * @description Return the ordered delta-band axis (put → ATM → call) the leg selector offers.
         *
         *     The single source of the band labels: the projection axis built by
         *     :meth:`ProjectionConfig.from_band` from the **one** band definition in
         *     ``qc_threshold.grid`` (``band_low_delta``/``band_high_delta``/``band_step``, ADR 0028) — the
         *     same numbers the projection emits and the grid QC validates, so the selector can never drift
         *     from the grid the platform actually produces. For the pinned ±30Δ *pas-2* grid that is the
         *     32 labels ``30dp … 02dp, atm, atmp, 02dc … 30dc``.
         *
         *     A configs bundle that cannot be loaded (a deployment with no ``configs/``) yields the
         *     in-memory default axis rather than a 500, so the selector is always populated.
         */
        get: operations["get_delta_bands_api_config_delta_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Config File
         * @description Return one config file's raw text, or a typed error payload.
         */
        get: operations["read_config_file_api_config__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constituents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constituents
         * @description Return the point-in-time constituent basket for an index, price-first.
         *
         *     ``index`` defaults to the context default underlying only as a label fallback; ``as_of``
         *     must be supplied for a historical view (it is passed verbatim to the resolver, never
         *     defaulted to today for a past date). When ``as_of`` is omitted the basket is resolved as of
         *     today's reconstruction date for a *current* view only.
         */
        get: operations["get_constituents_api_constituents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Return the per-expiry capture + per-tenor QC coverage for one underlying and date.
         */
        get: operations["get_coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return the operator dashboard status for a trade date (latest with data by default).
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/indices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Indices
         * @description Return the enabled indices (symbol + display name + currency), in registry order.
         *
         *     The symbol is the platform-wide vocabulary key (e.g. ``SX5E``); ``name`` is the display
         *     label (e.g. ``EURO STOXX 50``); ``currency`` is the index's ISO quote currency (e.g.
         *     ``EUR``), the single source the front uses to render monetized Greeks/PnL in the right
         *     currency symbol — never a hard-coded ``$`` (the blueprint requires the *correct* currency
         *     on monetized Greeks, 05-math-notes). The list is the registry's ``enabled`` set — the
         *     single source of which indices exist — so the front selector cannot list (or mis-label
         *     the currency of) an index the backend is not capturing.
         *
         *     A registry that cannot be loaded (no ``configs/`` bundle on this deployment) yields a
         *     labeled empty payload (``indices == []``), never a 500 — the selector then renders empty
         *     and disabled rather than fronting an error tile.
         */
        get: operations["get_indices_api_indices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description All jobs, most-recently-started first.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return one job's status, or a typed not-found payload.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price History
         * @description Return daily OHLC bars for one underlying over an optional ``[start, end]`` window.
         *
         *     ``start``/``end`` are inclusive ISO dates; either may be omitted for an open bound. A
         *     malformed date yields a labeled 400 (mirrors the surfaces router's ``bad_trade_date``); an
         *     unknown ticker or empty window yields an empty ``bars`` list with HTTP 200, never a 500.
         */
        get: operations["get_price_history_api_price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/price-history/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price History Batch
         * @description Return grouped OHLC histories for the requested underlyings.
         *
         *     Query callers can pass repeated ``underlyings=AAA&underlyings=BBB`` or a comma-separated
         *     value. ``start`` omitted means the bounded default window up to ``end``.
         */
        get: operations["get_price_history_batch_api_price_history_batch_get"];
        put?: never;
        /**
         * Post Price History Batch
         * @description POST variant for large baskets whose symbols should not be encoded into a long URL.
         */
        post: operations["post_price_history_batch_api_price_history_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description Capabilities of every known provider — drives the UI selector.
         */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recorded-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recorded Dates
         * @description Return the trade dates the front can show, plus the clean-coverage count.
         *
         *     ``dates``/``count`` are the **qc-clean, gap-free** days (every canonical EOD stage finished
         *     cleanly) — the operator-facing coverage figure, unchanged. ``available`` is the broader set
         *     the date picker actually offers: every day whose ``analytics`` stage produced a surface,
         *     **including qc-failing ones**, each tagged with its QC verdict (``pass``/``fail``/``unknown``).
         *     A degraded day stays selectable and is shown with its QC badge rather than hidden (cahier des
         *     charges §3.1 QC badge + §5 "show degraded states, don't mask them"). An empty ledger yields
         *     ``count == 0`` and empty lists.
         */
        get: operations["get_recorded_dates_api_recorded_dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk
         * @description Return net-sensitivity aggregates, optionally filtered to one portfolio.
         */
        get: operations["get_risk_api_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics
         * @description Return per-contract price/Greeks with the unit-carrying dollar layer.
         *
         *     Each dollar metric is read back with the explicit unit string of the pinned
         *     convention beside its raw per-unit Greek (the BFF metric contract, ADR 0036), so the
         *     front never receives a bare float. Optionally filtered to one underlying.
         */
        get: operations["get_metrics_api_risk_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolios
         * @description List the portfolio ids that have persisted risk aggregates.
         */
        get: operations["list_portfolios_api_risk_portfolios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenarios
         * @description Return stress-scenario PnL cells plus the reshaped (spot × vol) surface (WS 2B).
         *
         *     Two additive views over the same persisted ``scenario_results`` rows: ``cells`` (the
         *     per-contract list, unchanged — 2C attributes over it) and ``surface`` (the cartesian
         *     ``surf_`` grid reshaped into axes + a ``scenario_pnl`` z-grid for the 2B Plotly page). A
         *     missing partition / unknown portfolio yields an empty list and a labelled empty surface,
         *     never a 500. Serving is read-only — the cron is the sole writer (ADR 0034).
         */
        get: operations["get_scenarios_api_risk_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch Run
         * @description Launch a run job for the requested provider.
         */
        post: operations["launch_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/underlyings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Underlyings
         * @description Underlyings that already have a persisted surface, plus the context default.
         *
         *     Namespaced as ``/run/underlyings`` (not ``/underlyings``) to avoid shadowing the
         *     Codex market router's ``/api/underlyings`` fixture-selector in the combined app.
         */
        get: operations["list_run_underlyings_api_run_underlyings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Surface
         * @description Return the fitted SVI slices for an underlying (defaults to the context default).
         */
        get: operations["get_surface_api_surfaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surfaces/underlyings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Surface Underlyings
         * @description List the underlyings that have a persisted surface.
         */
        get: operations["list_surface_underlyings_api_surfaces_underlyings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticket/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticket Options
         * @description The selectable broker / time-in-force values, derived from the enums.
         *
         *     The single source for the web Ticket panel's selectors, so the front never hardcodes a
         *     parallel list that could drift from `TargetBroker` / `TimeInForce`.
         */
        get: operations["ticket_options_api_ticket_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticket/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Ticket
         * @description Build and preview an order ticket from a composed basket (read-only, paper).
         *
         *     Calls the pure builder and serializes the result. **Nothing is transmitted**; the broker is
         *     named and validated, never connected to. A malformed request is a labelled 400.
         */
        post: operations["preview_ticket_api_ticket_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness probe: 200 when the process is up (no infra reads).
         */
        get: operations["liveness_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RunRequest
         * @description The body of a run launch: which provider, and (optionally) which underlying.
         */
        RunRequest: {
            /**
             * Provider
             * @default SAMPLE
             */
            provider: string;
            /** Underlying */
            underlying?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analytics_api_analytics_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                trade_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attribution_api_attribution_get: {
        parameters: {
            query?: {
                trade_date?: string | null;
                portfolio_id?: string | null;
                level?: string;
                contract_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_basket_api_basket_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stress_basket_api_basket_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    commit_booking_api_booking_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_config_files_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_delta_bands_api_config_delta_bands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_config_file_api_config__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_constituents_api_constituents_get: {
        parameters: {
            query?: {
                index?: string | null;
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_coverage_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                trade_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: {
                trade_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_indices_api_indices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_price_history_api_price_history_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_price_history_batch_api_price_history_batch_get: {
        parameters: {
            query?: {
                underlyings?: string[] | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_price_history_batch_api_price_history_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_recorded_dates_api_recorded_dates_get: {
        parameters: {
            query?: {
                index?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_api_risk_get: {
        parameters: {
            query?: {
                portfolio_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_risk_metrics_get: {
        parameters: {
            query?: {
                underlying?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_risk_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_scenarios_api_risk_scenarios_get: {
        parameters: {
            query?: {
                portfolio_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_underlyings_api_run_underlyings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_surface_api_surfaces_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                trade_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_surface_underlyings_api_surfaces_underlyings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ticket_options_api_ticket_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_ticket_api_ticket_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    liveness_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
